language: ruby

rvm:
  #  - 2.0.0
  #  - 2.1.6
  #  - 2.2.2
  #  - 2.3.0
  - 2.4.0
  #  - ruby-head
  #  - jruby-19mode
  #  - jruby-9.1.5.0
  #  - jruby-head

os:
  - linux
#  - osx

sudo: false

branches:
  only:
    - master
    - coverity_scan

gemfile:
  - Gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      os: osx
    - rvm: jruby-19mode
      os: osx
    - rvm: jruby-9.1.5.0
      os: osx
    - rvm: jruby-head
      os: osx
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
      os: osx

env:
  global:
    - secure: "bWJR/alkUhovaZVn4EySamXsWsvAngLh/krZf3Jha6gYWGaf6HXFwB5gM9EaBIQsZKGECL9AKN0v8rX6tqSnXMKX2FgA9ClYvO0F60JviY6Ur6OT2rG0pm+WZZ1jzyGmf+5gVqiWF1/lM/tokdnj0Nw68OQwlNdc+DqxGXormO8="  # travis encrypt COVERITY_SCAN_TOKEN=...

before_install:
  # Skip build if branch is coverity_scan and this is the 1st job of the build matrix
  - test "$TRAVIS_BRANCH" != "coverity_scan" -o "${TRAVIS_JOB_NUMBER##*.}" = 1 || exit 0

addons:
  coverity_scan:
    project:
      name: "msgpack/msgpack-ruby"
      description: "Build submitted via Travis CI"
    notification_email: frsyuki@gmail.com
    build_command_prepend: "bundle exec rake compile && make -C tmp/x86_64-linux*/msgpack/*/ clean"
    build_command: "make -C tmp/x86_64-linux*/msgpack/*/"
    branch_pattern: coverity_scan

